export const ADD_USER = "ADD_USER";
export const SELECT_USER_ID = "SELECT_USER_ID";

export const OPEN_NEW_ORDER = "OPEN_NEW_ORDER";
export const CLOSE_ORDER = "CLOSE_ORDER";

export const ADD_ITEM_TO_ORDER = "ADD_ITEM_TO_ORDER";
// EDIT NOT NEEDED AS ADDING WITH THE SAME USER ID WILL OVERWRITE
// export const EDIT_ORDER_ITEM = "EDIT_ORDER_ITEM";
export const REMOVE_ITEM_FROM_ORDER = "REMOVE_ITEM_FROM_ORDER";

export const RESET_STATE = "RESET_STATE";
